function ccsdt_doubles!(EC::ECInfo, R2a, R2b, R2ab, T2a, T2b, T2ab, T3a, T3b, T3aab, T3abb, fij, fab, fIJ, fAB, fai, fAI, fia, fIA)
d_vvvv = load(EC,"d_vvvv")
@tensoropt R2a[c,d,i,j] -= 0.5 * d_vvvv[d,c,a,b] * T2a[a,b,i,j]
@tensoropt R2a[c,d,i,j] += 0.5 * d_vvvv[c,d,a,b] * T2a[a,b,i,j]
d_vvvv = nothing
d_VVVV = load(EC,"d_VVVV")
@tensoropt R2b[C,D,I,J] -= 0.5 * d_VVVV[C,D,B,A] * T2b[A,B,I,J]
@tensoropt R2b[C,D,I,J] += 0.5 * d_VVVV[D,C,B,A] * T2b[A,B,I,J]
d_VVVV = nothing
d_vVvV = load(EC,"d_vVvV")
@tensoropt R2ab[b,B,i,I] += 1 * d_vVvV[b,B,a,A] * T2ab[a,A,i,I]
d_vVvV = nothing
d_vovv = load(EC,"d_vovv")
@tensoropt R2ab[c,A,j,I] += 1 * d_vovv[c,i,b,a] * T3aab[b,a,A,j,i,I]
@tensoropt R2a[d,c,j,k] += 1 * d_vovv[c,i,b,a] * T3a[d,b,a,j,k,i]
@tensoropt R2a[c,d,j,k] -= 1 * d_vovv[c,i,b,a] * T3a[d,b,a,j,k,i]
d_vovv = nothing
d_VOVV = load(EC,"d_VOVV")
@tensoropt R2ab[a,C,i,J] += 1 * d_VOVV[C,I,B,A] * T3abb[a,B,A,i,J,I]
@tensoropt R2b[D,C,J,K] += 1 * d_VOVV[C,I,B,A] * T3b[D,B,A,J,K,I]
@tensoropt R2b[C,D,J,K] -= 1 * d_VOVV[C,I,B,A] * T3b[D,B,A,J,K,I]
d_VOVV = nothing
d_vOvV = load(EC,"d_vOvV")
@tensoropt R2ab[b,B,i,J] += 1 * d_vOvV[b,I,a,A] * T3abb[a,B,A,i,J,I]
@tensoropt R2a[c,b,i,j] += 1 * d_vOvV[b,I,a,A] * T3aab[c,a,A,i,j,I]
@tensoropt R2a[b,c,i,j] -= 1 * d_vOvV[b,I,a,A] * T3aab[c,a,A,i,j,I]
d_vOvV = nothing
d_vvoo = load(EC,"d_vvoo")
@tensoropt R2a[a,b,i,j] -= 1 * d_vvoo[b,a,i,j]
@tensoropt R2a[a,b,i,j] += 1 * d_vvoo[a,b,i,j]
d_vvoo = nothing
d_VVOO = load(EC,"d_VVOO")
@tensoropt R2b[A,B,I,J] -= 1 * d_VVOO[A,B,J,I]
@tensoropt R2b[A,B,I,J] += 1 * d_VVOO[B,A,J,I]
d_VVOO = nothing
d_vVoO = load(EC,"d_vVoO")
@tensoropt R2ab[a,A,i,I] += 1 * d_vVoO[a,A,i,I]
d_vVoO = nothing
d_vovo = load(EC,"d_vovo")
@tensoropt R2ab[b,A,j,I] -= 1 * d_vovo[b,i,a,j] * T2ab[a,A,i,I]
@tensoropt R2a[c,b,k,j] -= 1 * d_vovo[b,i,a,j] * T2a[c,a,k,i]
@tensoropt R2a[b,c,k,j] += 1 * d_vovo[b,i,a,j] * T2a[c,a,k,i]
@tensoropt R2a[c,b,j,k] += 1 * d_vovo[b,i,a,j] * T2a[c,a,k,i]
@tensoropt R2a[b,c,j,k] -= 1 * d_vovo[b,i,a,j] * T2a[c,a,k,i]
d_vovo = nothing
d_VOVO = load(EC,"d_VOVO")
@tensoropt R2ab[a,B,i,J] -= 1 * d_VOVO[B,I,A,J] * T2ab[a,A,i,I]
@tensoropt R2b[C,B,K,J] -= 1 * d_VOVO[B,I,A,J] * T2b[C,A,K,I]
@tensoropt R2b[B,C,K,J] += 1 * d_VOVO[B,I,A,J] * T2b[C,A,K,I]
@tensoropt R2b[C,B,J,K] += 1 * d_VOVO[B,I,A,J] * T2b[C,A,K,I]
@tensoropt R2b[B,C,J,K] -= 1 * d_VOVO[B,I,A,J] * T2b[C,A,K,I]
d_VOVO = nothing
d_vOvO = load(EC,"d_vOvO")
@tensoropt R2ab[b,A,i,J] -= 1 * d_vOvO[b,I,a,J] * T2ab[a,A,i,I]
d_vOvO = nothing
d_voov = load(EC,"d_voov")
@tensoropt R2ab[b,A,j,I] += 1 * d_voov[b,i,j,a] * T2ab[a,A,i,I]
@tensoropt R2a[c,b,k,j] += 1 * d_voov[b,i,j,a] * T2a[c,a,k,i]
@tensoropt R2a[b,c,k,j] -= 1 * d_voov[b,i,j,a] * T2a[c,a,k,i]
@tensoropt R2a[c,b,j,k] -= 1 * d_voov[b,i,j,a] * T2a[c,a,k,i]
@tensoropt R2a[b,c,j,k] += 1 * d_voov[b,i,j,a] * T2a[c,a,k,i]
d_voov = nothing
d_VOOV = load(EC,"d_VOOV")
@tensoropt R2ab[a,B,i,J] += 1 * d_VOOV[B,I,J,A] * T2ab[a,A,i,I]
@tensoropt R2b[C,B,K,J] += 1 * d_VOOV[B,I,J,A] * T2b[C,A,K,I]
@tensoropt R2b[B,C,K,J] -= 1 * d_VOOV[B,I,J,A] * T2b[C,A,K,I]
@tensoropt R2b[C,B,J,K] -= 1 * d_VOOV[B,I,J,A] * T2b[C,A,K,I]
@tensoropt R2b[B,C,J,K] += 1 * d_VOOV[B,I,J,A] * T2b[C,A,K,I]
d_VOOV = nothing
d_vOoV = load(EC,"d_vOoV")
@tensoropt R2ab[a,B,i,J] += 1 * d_vOoV[a,I,i,A] * T2b[B,A,J,I]
@tensoropt R2a[b,a,j,i] += 1 * d_vOoV[a,I,i,A] * T2ab[b,A,j,I]
@tensoropt R2a[a,b,j,i] -= 1 * d_vOoV[a,I,i,A] * T2ab[b,A,j,I]
@tensoropt R2a[b,a,i,j] -= 1 * d_vOoV[a,I,i,A] * T2ab[b,A,j,I]
@tensoropt R2a[a,b,i,j] += 1 * d_vOoV[a,I,i,A] * T2ab[b,A,j,I]
d_vOoV = nothing
d_oooo = load(EC,"d_oooo")
@tensoropt R2a[a,b,k,l] -= 0.5 * d_oooo[j,i,l,k] * T2a[b,a,i,j]
@tensoropt R2a[a,b,k,l] += 0.5 * d_oooo[j,i,l,k] * T2a[a,b,i,j]
d_oooo = nothing
d_OOOO = load(EC,"d_OOOO")
@tensoropt R2b[A,B,K,L] -= 0.5 * d_OOOO[J,I,L,K] * T2b[B,A,I,J]
@tensoropt R2b[A,B,K,L] += 0.5 * d_OOOO[J,I,L,K] * T2b[A,B,I,J]
d_OOOO = nothing
d_oOoO = load(EC,"d_oOoO")
@tensoropt R2ab[a,A,j,J] += 1 * d_oOoO[i,I,j,J] * T2ab[a,A,i,I]
d_oOoO = nothing
d_oovo = load(EC,"d_oovo")
@tensoropt R2ab[b,A,k,I] -= 1 * d_oovo[j,i,a,k] * T3aab[b,a,A,i,j,I]
@tensoropt R2a[b,c,l,k] -= 1 * d_oovo[j,i,a,k] * T3a[b,c,a,l,i,j]
@tensoropt R2a[b,c,k,l] += 1 * d_oovo[j,i,a,k] * T3a[b,c,a,l,i,j]
d_oovo = nothing
d_OOVO = load(EC,"d_OOVO")
@tensoropt R2ab[a,B,i,K] -= 1 * d_OOVO[J,I,A,K] * T3abb[a,B,A,i,I,J]
@tensoropt R2b[B,C,L,K] -= 1 * d_OOVO[J,I,A,K] * T3b[B,C,A,L,I,J]
@tensoropt R2b[B,C,K,L] += 1 * d_OOVO[J,I,A,K] * T3b[B,C,A,L,I,J]
d_OOVO = nothing
d_oOvO = load(EC,"d_oOvO")
@tensoropt R2ab[b,A,j,J] -= 1 * d_oOvO[i,I,a,J] * T3aab[b,a,A,j,i,I]
@tensoropt R2b[A,B,K,J] -= 1 * d_oOvO[i,I,a,J] * T3abb[a,A,B,i,K,I]
@tensoropt R2b[A,B,J,K] += 1 * d_oOvO[i,I,a,J] * T3abb[a,A,B,i,K,I]
d_oOvO = nothing
d_oOoV = load(EC,"d_oOoV")
@tensoropt R2ab[a,B,j,J] -= 1 * d_oOoV[i,I,j,A] * T3abb[a,B,A,i,J,I]
@tensoropt R2a[a,b,k,j] -= 1 * d_oOoV[i,I,j,A] * T3aab[a,b,A,k,i,I]
@tensoropt R2a[a,b,j,k] += 1 * d_oOoV[i,I,j,A] * T3aab[a,b,A,k,i,I]
d_oOoV = nothing
d_oVvO = load(EC,"d_oVvO")
@tensoropt R2ab[b,A,j,I] += 1 * d_oVvO[i,A,a,I] * T2a[b,a,j,i]
@tensoropt R2b[B,A,J,I] += 1 * d_oVvO[i,A,a,I] * T2ab[a,B,i,J]
@tensoropt R2b[A,B,J,I] -= 1 * d_oVvO[i,A,a,I] * T2ab[a,B,i,J]
@tensoropt R2b[B,A,I,J] -= 1 * d_oVvO[i,A,a,I] * T2ab[a,B,i,J]
@tensoropt R2b[A,B,I,J] += 1 * d_oVvO[i,A,a,I] * T2ab[a,B,i,J]
d_oVvO = nothing
d_oVoV = load(EC,"d_oVoV")
@tensoropt R2ab[a,B,j,I] -= 1 * d_oVoV[i,B,j,A] * T2ab[a,A,i,I]
d_oVoV = nothing
oovv = ints2(EC,"oovv")
@tensoropt R2ab[a,A,i,I] -= 1 * oovv[k,j,b,c] * T2a[a,b,i,j] * T2ab[c,A,k,I]
@tensoropt R2ab[a,A,i,I] -= 1 * oovv[k,j,c,b] * T2a[c,b,i,j] * T2ab[a,A,k,I]
@tensoropt R2ab[a,A,i,I] -= 1 * oovv[k,j,c,b] * T2a[b,a,j,k] * T2ab[c,A,i,I]
@tensoropt R2ab[a,A,i,I] += 1 * oovv[k,j,c,b] * T2a[a,b,i,j] * T2ab[c,A,k,I]
@tensoropt R2b[B,A,I,J] += 1 * oovv[j,i,a,b] * T2ab[a,A,i,I] * T2ab[b,B,j,J]
@tensoropt R2b[A,B,I,J] -= 1 * oovv[j,i,a,b] * T2ab[a,A,i,I] * T2ab[b,B,j,J]
@tensoropt R2b[B,A,I,J] -= 1 * oovv[j,i,b,a] * T2ab[a,A,i,I] * T2ab[b,B,j,J]
@tensoropt R2b[A,B,I,J] += 1 * oovv[j,i,b,a] * T2ab[a,A,i,I] * T2ab[b,B,j,J]
@tensoropt R2a[a,b,i,j] -= 0.25 * oovv[l,k,d,c] * T2a[b,a,k,l] * T2a[c,d,i,j]
@tensoropt R2a[a,b,i,j] += 0.25 * oovv[l,k,d,c] * T2a[a,b,k,l] * T2a[c,d,i,j]
@tensoropt R2a[b,a,i,j] += 1 * oovv[l,k,c,d] * T2a[a,c,i,k] * T2a[b,d,j,l]
@tensoropt R2a[a,b,i,j] -= 1 * oovv[l,k,c,d] * T2a[a,c,i,k] * T2a[b,d,j,l]
@tensoropt R2a[a,b,j,i] -= 1 * oovv[l,k,d,c] * T2a[d,c,i,k] * T2a[a,b,j,l]
@tensoropt R2a[a,b,i,j] += 1 * oovv[l,k,d,c] * T2a[d,c,i,k] * T2a[a,b,j,l]
@tensoropt R2a[b,a,i,j] -= 1 * oovv[l,k,d,c] * T2a[c,a,k,l] * T2a[b,d,i,j]
@tensoropt R2a[a,b,i,j] += 1 * oovv[l,k,d,c] * T2a[c,a,k,l] * T2a[b,d,i,j]
@tensoropt R2a[b,a,i,j] -= 1 * oovv[l,k,d,c] * T2a[a,c,i,k] * T2a[b,d,j,l]
@tensoropt R2a[a,b,i,j] += 1 * oovv[l,k,d,c] * T2a[a,c,i,k] * T2a[b,d,j,l]
oovv = nothing
OOVV = ints2(EC,"OOVV")
@tensoropt R2ab[a,A,i,I] -= 1 * OOVV[K,J,C,B] * T2b[C,B,I,J] * T2ab[a,A,i,K]
@tensoropt R2ab[a,A,i,I] -= 1 * OOVV[K,J,C,B] * T2b[B,A,J,K] * T2ab[a,C,i,I]
@tensoropt R2ab[a,A,i,I] -= 1 * OOVV[K,J,B,C] * T2ab[a,B,i,J] * T2b[A,C,I,K]
@tensoropt R2ab[a,A,i,I] += 1 * OOVV[K,J,C,B] * T2ab[a,B,i,J] * T2b[A,C,I,K]
@tensoropt R2b[A,B,I,J] -= 0.25 * OOVV[L,K,D,C] * T2b[B,A,K,L] * T2b[C,D,I,J]
@tensoropt R2b[A,B,I,J] += 0.25 * OOVV[L,K,D,C] * T2b[A,B,K,L] * T2b[C,D,I,J]
@tensoropt R2b[B,A,I,J] += 1 * OOVV[L,K,C,D] * T2b[A,C,I,K] * T2b[B,D,J,L]
@tensoropt R2b[A,B,I,J] -= 1 * OOVV[L,K,C,D] * T2b[A,C,I,K] * T2b[B,D,J,L]
@tensoropt R2b[A,B,J,I] -= 1 * OOVV[L,K,D,C] * T2b[D,C,I,K] * T2b[A,B,J,L]
@tensoropt R2b[A,B,I,J] += 1 * OOVV[L,K,D,C] * T2b[D,C,I,K] * T2b[A,B,J,L]
@tensoropt R2b[B,A,I,J] -= 1 * OOVV[L,K,D,C] * T2b[C,A,K,L] * T2b[B,D,I,J]
@tensoropt R2b[A,B,I,J] += 1 * OOVV[L,K,D,C] * T2b[C,A,K,L] * T2b[B,D,I,J]
@tensoropt R2b[B,A,I,J] -= 1 * OOVV[L,K,D,C] * T2b[A,C,I,K] * T2b[B,D,J,L]
@tensoropt R2b[A,B,I,J] += 1 * OOVV[L,K,D,C] * T2b[A,C,I,K] * T2b[B,D,J,L]
@tensoropt R2a[b,a,i,j] += 1 * OOVV[J,I,A,B] * T2ab[a,A,i,I] * T2ab[b,B,j,J]
@tensoropt R2a[a,b,i,j] -= 1 * OOVV[J,I,A,B] * T2ab[a,A,i,I] * T2ab[b,B,j,J]
@tensoropt R2a[b,a,i,j] -= 1 * OOVV[J,I,B,A] * T2ab[a,A,i,I] * T2ab[b,B,j,J]
@tensoropt R2a[a,b,i,j] += 1 * OOVV[J,I,B,A] * T2ab[a,A,i,I] * T2ab[b,B,j,J]
OOVV = nothing
oOvV = ints2(EC,"oOvV")
@tensoropt R2ab[a,A,i,I] += 1 * oOvV[j,J,b,B] * T2ab[a,A,j,J] * T2ab[b,B,i,I]
@tensoropt R2ab[a,A,i,I] -= 1 * oOvV[j,J,b,B] * T2ab[b,B,j,I] * T2ab[a,A,i,J]
@tensoropt R2ab[a,A,i,I] += 1 * oOvV[j,J,b,B] * T2ab[b,A,i,J] * T2ab[a,B,j,I]
@tensoropt R2ab[a,A,i,I] -= 1 * oOvV[j,J,b,B] * T2ab[b,A,j,J] * T2ab[a,B,i,I]
@tensoropt R2ab[a,A,i,I] -= 1 * oOvV[j,J,b,B] * T2ab[b,B,i,J] * T2ab[a,A,j,I]
@tensoropt R2ab[a,A,i,I] -= 1 * oOvV[j,J,b,B] * T2ab[a,B,j,J] * T2ab[b,A,i,I]
@tensoropt R2ab[a,A,i,I] += 1 * oOvV[j,J,b,B] * T2ab[a,B,i,J] * T2ab[b,A,j,I]
@tensoropt R2ab[a,A,i,I] += 1 * oOvV[j,J,b,B] * T2a[a,b,i,j] * T2b[A,B,I,J]
@tensoropt R2b[A,B,J,I] -= 1 * oOvV[i,K,a,C] * T2ab[a,C,i,I] * T2b[A,B,J,K]
@tensoropt R2b[A,B,I,J] += 1 * oOvV[i,K,a,C] * T2ab[a,C,i,I] * T2b[A,B,J,K]
@tensoropt R2b[B,A,I,J] -= 1 * oOvV[i,K,a,C] * T2ab[a,A,i,K] * T2b[B,C,I,J]
@tensoropt R2b[A,B,I,J] += 1 * oOvV[i,K,a,C] * T2ab[a,A,i,K] * T2b[B,C,I,J]
@tensoropt R2b[B,A,I,J] -= 1 * oOvV[i,K,a,C] * T2b[A,C,I,K] * T2ab[a,B,i,J]
@tensoropt R2b[A,B,I,J] += 1 * oOvV[i,K,a,C] * T2b[A,C,I,K] * T2ab[a,B,i,J]
@tensoropt R2b[B,A,I,J] -= 1 * oOvV[i,K,a,C] * T2ab[a,A,i,I] * T2b[B,C,J,K]
@tensoropt R2b[A,B,I,J] += 1 * oOvV[i,K,a,C] * T2ab[a,A,i,I] * T2b[B,C,J,K]
@tensoropt R2a[a,b,j,i] -= 1 * oOvV[k,I,c,A] * T2ab[c,A,i,I] * T2a[a,b,j,k]
@tensoropt R2a[a,b,i,j] += 1 * oOvV[k,I,c,A] * T2ab[c,A,i,I] * T2a[a,b,j,k]
@tensoropt R2a[b,a,i,j] -= 1 * oOvV[k,I,c,A] * T2ab[a,A,k,I] * T2a[b,c,i,j]
@tensoropt R2a[a,b,i,j] += 1 * oOvV[k,I,c,A] * T2ab[a,A,k,I] * T2a[b,c,i,j]
@tensoropt R2a[b,a,i,j] -= 1 * oOvV[k,I,c,A] * T2ab[a,A,i,I] * T2a[b,c,j,k]
@tensoropt R2a[a,b,i,j] += 1 * oOvV[k,I,c,A] * T2ab[a,A,i,I] * T2a[b,c,j,k]
@tensoropt R2a[b,a,i,j] -= 1 * oOvV[k,I,c,A] * T2a[a,c,i,k] * T2ab[b,A,j,I]
@tensoropt R2a[a,b,i,j] += 1 * oOvV[k,I,c,A] * T2a[a,c,i,k] * T2ab[b,A,j,I]
oOvV = nothing
d_oVvV = load(EC,"d_oVvV")
@tensoropt R2ab[b,B,j,I] += 1 * d_oVvV[i,B,a,A] * T3aab[b,a,A,j,i,I]
@tensoropt R2b[C,B,I,J] += 1 * d_oVvV[i,B,a,A] * T3abb[a,C,A,i,I,J]
@tensoropt R2b[B,C,I,J] -= 1 * d_oVvV[i,B,a,A] * T3abb[a,C,A,i,I,J]
d_oVvV = nothing
@tensoropt R2a[b,c,j,k] += 1 * fia[i,a] * T3a[b,c,a,j,k,i]
@tensoropt R2a[a,b,i,j] += 1 * fIA[I,A] * T3aab[a,b,A,i,j,I]
@tensoropt R2a[a,b,j,k] += 1 * fij[i,j] * T2a[a,b,k,i]
@tensoropt R2a[a,b,k,j] -= 1 * fij[i,j] * T2a[a,b,k,i]
@tensoropt R2a[b,c,i,j] -= 1 * fab[b,a] * T2a[c,a,i,j]
@tensoropt R2a[c,b,i,j] += 1 * fab[b,a] * T2a[c,a,i,j]
@tensoropt R2b[A,B,I,J] += 1 * fia[i,a] * T3abb[a,A,B,i,I,J]
@tensoropt R2b[B,C,J,K] += 1 * fIA[I,A] * T3b[B,C,A,J,K,I]
@tensoropt R2b[A,B,J,K] += 1 * fIJ[I,J] * T2b[A,B,K,I]
@tensoropt R2b[A,B,K,J] -= 1 * fIJ[I,J] * T2b[A,B,K,I]
@tensoropt R2b[B,C,I,J] -= 1 * fAB[B,A] * T2b[C,A,I,J]
@tensoropt R2b[C,B,I,J] += 1 * fAB[B,A] * T2b[C,A,I,J]
@tensoropt R2ab[b,A,j,I] += 1 * fia[i,a] * T3aab[b,a,A,j,i,I]
@tensoropt R2ab[a,B,i,J] += 1 * fIA[I,A] * T3abb[a,B,A,i,J,I]
@tensoropt R2ab[a,A,j,I] -= 1 * fij[i,j] * T2ab[a,A,i,I]
@tensoropt R2ab[b,A,i,I] += 1 * fab[b,a] * T2ab[a,A,i,I]
@tensoropt R2ab[a,B,i,I] += 1 * fAB[B,A] * T2ab[a,A,i,I]
@tensoropt R2ab[a,A,i,J] -= 1 * fIJ[I,J] * T2ab[a,A,i,I]
end