"""
    calc_df_lt_sos_mp2(EC::ECInfo)

  Perform density-fitted Laplace-transformed SOS MP2 calculation.

  Args:
    EC: ECInfo object

  Returns:
    OutDict with keys "E", "ESS", "EOS", "EO" for MP2 correlation energy, SS, OS, and O contributions.
"""
function calc_df_lt_sos_mp2(EC::ECInfo{T}) where T
  t1 = time_ns()
  print_info("DF-LT-SOS-MP2")
  SP = EC.space
  eps = real.(load1idx(EC, "e_m"))
  ϵo = eps[SP['o']]
  ϵv = eps[SP['v']]
  nocc = length(SP['o'])
  nvir = length(SP['v'])
  w_laplace, t_laplace = get_laplace_quadrature(ϵo, ϵv, EC.options.laplace.npoints,
                                                algo=EC.options.laplace.algo)
  if EC.fd.df3idx
    mmLfile, mmL = mmap3idx(EC, "mmL")
    voL = mmL[SP['v'], SP['o'], :]
    close(mmLfile)
    nL = size(voL, 3)
    t1 = print_time(EC, t1, "DF-LT-SOS-MP2: load 3-index integrals", 1)
    EMP2OS = 0.0
    TvoL = similar(voL)
    for q in eachindex(t_laplace)
      tq = t_laplace[q]
      wq = w_laplace[q]
      for a in 1:nvir, i in 1:nocc
        fac = exp(-tq * (ϵv[a] - ϵo[i]))
        for L in 1:nL
          TvoL[a,i,L] = voL[a,i,L] * fac
        end
      end
      @mtensor VT[L,K] := conj(voL[a,i,L]) * TvoL[a,i,K]
      @mtensor EMP2OS += wq * VT[L,K] * VT[L,K]
    end
    t1 = print_time(EC, t1, "energy calculation", 1)
    EMP2SS = 0.0
    ESOSMP2 = EMP2OS * EC.options.cc.mp2_sosfac
    return OutDict("E"=>ESOSMP2, "ESS"=>EMP2SS, "EOS"=>EMP2OS, "EO"=>0.0)
  end
  cMO = load_orbitals(EC)
  if !is_restricted(cMO) || SP['o'] != SP['O']
    error("Unrestricted orbitals not supported in DF-LT-SOS-MP2.")
  end
  c_Am = cMO[1]
  nA = size(c_Am, 1)
  c_Ao = c_Am[:,SP['o']]
  c_Av = c_Am[:,SP['v']]
  C_PL = load2idx(EC, "C_PL")
  nP, nL = size(C_PL)
  voP = zeros(nvir, nocc, nP)
  bao = generate_basis(EC, "ao")
  bfit = generate_basis(EC, "mpfit")
  Pbatches = BasisBatcher(bao, bfit)
  maxP = max_batch_length(Pbatches)
  PBlks = get_spaceblocks(1:nP)
  maxP1 = maximum(length, PBlks)
  lenbuf = auto_calc_buffer_length4calc_df_lt_sos_mp2(nocc, nvir, nA, nL, nP, maxP, maxP1)
  lencbuf = buffer_size_3idx(Pbatches)
  @buffer buf(lenbuf) begin
  # @print_buffer_usage buf begin
  @buffer cbuf(Cdouble, lencbuf) begin
  for Pblk in Pbatches
    P = range(Pblk)
    lenP = length(P)
    oAP = alloc!(buf, nocc, nA, lenP)
    AAP = alloc!(buf, nA, nA, lenP)
    eri_2e3idx!(AAP, cbuf, Pblk)
    @mtensor oAP[i,ν,P] = c_Ao[μ,i] * AAP[μ,ν,P]
    drop!(buf, AAP)
    v!voP = @mview voP[:,:,P]
    @mtensor v!voP[a,i,P] = c_Av[ν,a] * oAP[i,ν,P]
    drop!(buf, oAP)
  end
  end #cbuf buffer
  t1 = print_time(EC, t1, "DF-LT-SOS-MP2: 3-index integrals", 1)
  # transform the integrals with Laplace points and add to OS energy
  EMP2OS = 0.0
  for q in eachindex(t_laplace)
    tq = t_laplace[q]
    wq = w_laplace[q]
    VT = zeros(nL, nL)
    for P in PBlks
      lenP1 = length(P)
      VT_PP = alloc!(buf, nP, lenP1)
      TvoP = alloc!(buf, nvir, nocc, lenP1)
      v!voP = @mview voP[:,:,P]
      for a in 1:nvir, i in 1:nocc
        fac = exp(-tq * (ϵv[a] - ϵo[i]))
        for P in 1:lenP1
          TvoP[a,i,P] = v!voP[a,i,P] * fac
        end
      end
      @mtensor VT_PP[Q,P] = voP[a,i,Q] * TvoP[a,i,P]
      drop!(buf, TvoP) 
      VT_LP = alloc!(buf, nL, lenP1)
      @mtensor VT_LP[L,P] = VT_PP[Q,P] * C_PL[Q,L]
      M_PL = alloc!(buf, lenP1, nL)
      M_PL .= @view C_PL[P,:]
      @mtensor VT[L,K] += VT_LP[L,P] * M_PL[P,K] 
      drop!(buf, VT_PP, VT_LP, M_PL)
    end
    @mtensor EMP2OS += wq * VT[L,K] * VT[L,K]
  end
  t1 = print_time(EC, t1, "energy calculation", 1)
  # end # print_buffer_usage
  end # buf buffer
  EMP2SS = 0.0
  ESOSMP2 = EMP2OS * EC.options.cc.mp2_sosfac
  return OutDict("E"=>ESOSMP2, "ESS"=>EMP2SS, "EOS"=>EMP2OS, "EO"=>0.0)
end

# Function to calculate length for buffer(s) buf
# autogenerated by @print_buffer_usage
function auto_calc_buffer_length4calc_df_lt_sos_mp2(nocc, nvir, nA, nL, nP, lenP, lenP1)
    buf = [0, 0]
    begin
        begin
            oAP = pseudo_alloc!(buf, nocc, nA, lenP)
            AAP = pseudo_alloc!(buf, nA, nA, lenP)
            pseudo_drop!(buf, AAP)
            pseudo_drop!(buf, oAP)
        end
    end
    begin
        begin
            VT_PP = pseudo_alloc!(buf, nP, lenP1)
            TvoP = pseudo_alloc!(buf, nvir, nocc, lenP1)
            pseudo_drop!(buf, TvoP)
            VT_LP = pseudo_alloc!(buf, nL, lenP1)
            M_PL = pseudo_alloc!(buf, lenP1, nL)
            pseudo_drop!(buf, VT_PP, VT_LP, M_PL)
        end
    end
    return buf[2]
end
